# Generated by Django 2.2 on 2025-02-13 08:27

import company.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyIncorporation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_type', models.CharField(choices=[('private limited', 'Private Limited Company'), ('sole proprietorship', 'Solo Proprietorship'), ('llp', 'LLP'), ('public limited', 'Public Limited Company'), ('section8', 'Section 8 Company'), ('one person', 'One-Person Company'), ('partnership', 'Partnership'), ('any other', 'Any Other')], max_length=30)),
                ('proposed_company_name1', models.CharField(max_length=60, unique=True)),
                ('proposed_company_name2', models.CharField(blank=True, max_length=60, null=True)),
                ('proposed_company_name3', models.CharField(blank=True, max_length=60, null=True)),
                ('business_objective', models.TextField()),
                ('business_activity', models.CharField(blank=True, choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D'), ('e', 'E')], max_length=30, null=True)),
                ('nic_code', models.PositiveIntegerField(blank=True, null=True)),
                ('address1', models.TextField(blank=True, max_length=100, null=True)),
                ('address2', models.TextField(blank=True, null=True)),
                ('ownership_type', models.CharField(choices=[('ownership1', 'Ownership1'), ('ownership2', 'Ownership2'), ('ownership3', 'Ownership3')], max_length=30)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('state', models.CharField(blank=True, max_length=30, null=True)),
                ('pincode', models.PositiveIntegerField(blank=True, null=True)),
                ('utility_bill', models.FileField(blank=True, null=True, upload_to=company.models.upload_to_basic_details)),
                ('noc', models.FileField(blank=True, null=True, upload_to=company.models.upload_to_basic_details)),
                ('rental_agreement', models.FileField(blank=True, null=True, upload_to=company.models.upload_to_basic_details)),
                ('property_tax_receipt', models.FileField(blank=True, null=True, upload_to=company.models.upload_to_basic_details)),
            ],
        ),
        migrations.CreateModel(
            name='ShareHoldersInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_shareholder', models.CharField(choices=[('individual', 'Individual'), ('company', 'Company')], max_length=10)),
                ('shareholder_first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('shareholder_last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('entity_name', models.CharField(blank=True, max_length=30, null=True)),
                ('cin_number', models.CharField(blank=True, max_length=30, null=True)),
                ('authorised_representative', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.PositiveIntegerField(blank=True, null=True)),
                ('percentage_of_holding', models.DecimalField(decimal_places=2, max_digits=10)),
                ('address1', models.TextField(blank=True, null=True)),
                ('address2', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('state', models.CharField(blank=True, max_length=30, null=True)),
                ('pincode', models.PositiveIntegerField(blank=True, null=True)),
                ('pan_card_file', models.FileField(blank=True, null=True, upload_to=company.models.upload_to_shareholder_information)),
                ('proof_address', models.CharField(blank=True, choices=[('aadhar card', 'Aadhar Card'), ('voter id', 'Voter ID'), ('passport', 'Passport'), ('driving license', 'Driving License'), ('utility bill', 'Utility Bill')], max_length=30, null=True)),
                ('proof_address_file', models.FileField(blank=True, null=True, upload_to=company.models.upload_to_shareholder_information)),
                ('bank_statement_file', models.FileField(blank=True, null=True, upload_to=company.models.upload_to_shareholder_information)),
                ('board_resolution', models.FileField(blank=True, default=None, null=True, upload_to=company.models.upload_to_shareholder_information)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shareholders_details', to='company.CompanyIncorporation')),
            ],
        ),
        migrations.CreateModel(
            name='DirectorsInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director_first_name', models.CharField(max_length=60)),
                ('director_middle_name', models.CharField(blank=True, max_length=60, null=True)),
                ('director_last_name', models.TextField(max_length=60)),
                ('father_first_name', models.CharField(max_length=60)),
                ('father_middle_name', models.CharField(blank=True, max_length=60, null=True)),
                ('father_last_name', models.CharField(max_length=60)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=30)),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(choices=[('indian', 'Indian'), ('not a indian', 'Not a Indian')], max_length=30)),
                ('education', models.CharField(choices=[('no formal education', 'No Formal Education'), ('primary education', 'Primary Education'), ('secondary education', 'Secondary Education'), ('bachelor degree', 'Bachelor Degree'), ('master degree', 'Master Degree'), ('high education', 'High Education')], max_length=30)),
                ('address1', models.TextField()),
                ('address2', models.TextField(blank=True)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('pincode', models.PositiveIntegerField()),
                ('proof_address', models.CharField(choices=[('aadhar card', 'Aadhar Card'), ('voter id', 'Voter ID'), ('passport', 'Passport'), ('driving license', 'Driving License'), ('utility bill', 'Utility Bill')], max_length=30)),
                ('proof_address_file', models.FileField(upload_to=company.models.upload_to_director_information)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.PositiveIntegerField()),
                ('pan_number', models.CharField(max_length=30)),
                ('pan_number_file', models.FileField(upload_to=company.models.upload_to_director_information)),
                ('aadhar_card_number', models.BigIntegerField()),
                ('aadhar_card_file', models.FileField(upload_to=company.models.upload_to_director_information)),
                ('din', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=30)),
                ('din_number', models.CharField(blank=True, max_length=30, null=True)),
                ('details_of_existing_directorships', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=30)),
                ('existing_company_name', models.CharField(blank=True, max_length=60, null=True)),
                ('existing_cin', models.CharField(blank=True, max_length=60, null=True)),
                ('existing_type_of_company', models.CharField(blank=True, max_length=30, null=True)),
                ('existing_position_herd', models.CharField(blank=True, max_length=30, null=True)),
                ('existing_date', models.CharField(blank=True, max_length=30, null=True)),
                ('passport_size_photo', models.FileField(upload_to=company.models.upload_to_director_information)),
                ('dsc', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=30)),
                ('role_in_the_company', models.CharField(max_length=30)),
                ('director_also_shareholder', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=30)),
                ('no_of_shares', models.PositiveIntegerField()),
                ('percentage_of_holdings', models.DecimalField(decimal_places=2, max_digits=15)),
                ('paid_up_cash_contribution', models.DecimalField(decimal_places=2, max_digits=15)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directors', to='company.CompanyIncorporation')),
            ],
        ),
        migrations.CreateModel(
            name='AuthorizedAndPaidUpCapital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorised_share_capital', models.DecimalField(decimal_places=2, max_digits=15)),
                ('paid_up_share_capital', models.DecimalField(decimal_places=2, max_digits=15)),
                ('face_value_per_share', models.DecimalField(decimal_places=2, max_digits=10)),
                ('number_of_shares', models.PositiveIntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capital_details', to='company.CompanyIncorporation')),
            ],
        ),
    ]
